/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package biometric_authentication_hand;

import java.nio.channels.Channels;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author Himashi Nethinika
 */
public class LoginForm extends javax.swing.JFrame {

    /**
     * Creates new form UserView
     */
    public LoginForm() {
        initComponents();
        setLocationRelativeTo(null);
    }

    public LoginForm(String text) {
        initComponents();
        setLocationRelativeTo(null);
        myButton.setText(text);
        if("LOG IN".equals(myButton.getText())){
            userNameLabel.setVisible(false);
            userNameTextField.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mainPanel = new javax.swing.JPanel();
        titlePanel = new javax.swing.JPanel();
        addUserLabel = new javax.swing.JLabel();
        imagePanel = new javax.swing.JPanel();
        handPanel = new javax.swing.JPanel();
        handPic = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        dataPanel = new javax.swing.JPanel();
        bluePanel = new javax.swing.JPanel();
        blueLabel = new javax.swing.JLabel();
        blueLabel1 = new javax.swing.JLabel();
        blueLabel2 = new javax.swing.JLabel();
        blueLabel3 = new javax.swing.JLabel();
        blueLabel4 = new javax.swing.JLabel();
        blueLabel5 = new javax.swing.JLabel();
        blueTextField1 = new javax.swing.JTextField();
        blueTextField2 = new javax.swing.JTextField();
        blueTextField3 = new javax.swing.JTextField();
        blueTextField4 = new javax.swing.JTextField();
        blueTextField5 = new javax.swing.JTextField();
        bluePanel1 = new javax.swing.JPanel();
        blueLabel6 = new javax.swing.JLabel();
        blueLabel7 = new javax.swing.JLabel();
        blueLabel8 = new javax.swing.JLabel();
        blueLabel9 = new javax.swing.JLabel();
        blueLabel10 = new javax.swing.JLabel();
        blueLabel11 = new javax.swing.JLabel();
        blueTextField6 = new javax.swing.JTextField();
        blueTextField7 = new javax.swing.JTextField();
        blueTextField8 = new javax.swing.JTextField();
        blueTextField9 = new javax.swing.JTextField();
        blueTextField10 = new javax.swing.JTextField();
        bluePanel2 = new javax.swing.JPanel();
        blueLabel12 = new javax.swing.JLabel();
        blueLabel13 = new javax.swing.JLabel();
        blueLabel14 = new javax.swing.JLabel();
        blueLabel15 = new javax.swing.JLabel();
        blueLabel16 = new javax.swing.JLabel();
        blueTextField11 = new javax.swing.JTextField();
        blueTextField12 = new javax.swing.JTextField();
        blueTextField13 = new javax.swing.JTextField();
        blueTextField14 = new javax.swing.JTextField();
        bluePanel3 = new javax.swing.JPanel();
        blueLabel18 = new javax.swing.JLabel();
        blueLabel19 = new javax.swing.JLabel();
        blueLabel20 = new javax.swing.JLabel();
        blueTextField16 = new javax.swing.JTextField();
        blueTextField17 = new javax.swing.JTextField();
        buttonPanel = new javax.swing.JPanel();
        myButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        userNameLabel = new javax.swing.JLabel();
        userNameTextField = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DO_NOTHING_ON_CLOSE);
        setResizable(false);

        mainPanel.setBackground(new java.awt.Color(255, 255, 255));

        titlePanel.setBackground(new java.awt.Color(255, 255, 255));

        addUserLabel.setBackground(new java.awt.Color(204, 255, 255));
        addUserLabel.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        addUserLabel.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        addUserLabel.setText("Biometric Autentication");

        javax.swing.GroupLayout titlePanelLayout = new javax.swing.GroupLayout(titlePanel);
        titlePanel.setLayout(titlePanelLayout);
        titlePanelLayout.setHorizontalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(addUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        titlePanelLayout.setVerticalGroup(
            titlePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(titlePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(addUserLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 32, Short.MAX_VALUE)
                .addContainerGap())
        );

        imagePanel.setBackground(new java.awt.Color(255, 255, 255));

        handPanel.setBackground(new java.awt.Color(255, 255, 255));

        handPic.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Hand_structure.PNG"))); // NOI18N

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jTextArea1.setText("1.Use this picture as sample to Enter your data in\nmillimeter(mm)\n\n2. All fields ara mandatory.");
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout handPanelLayout = new javax.swing.GroupLayout(handPanel);
        handPanel.setLayout(handPanelLayout);
        handPanelLayout.setHorizontalGroup(
            handPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(handPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addComponent(handPic, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );
        handPanelLayout.setVerticalGroup(
            handPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(handPanelLayout.createSequentialGroup()
                .addComponent(handPic, javax.swing.GroupLayout.PREFERRED_SIZE, 481, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        blueLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Blue.PNG"))); // NOI18N
        blueLabel.setText("Input details 1-5");

        blueLabel1.setText("Input for 1 ");

        blueLabel2.setText("Input for 2 ");

        blueLabel3.setText("Input for 3 ");

        blueLabel4.setText("Input for 4 ");

        blueLabel5.setText("Input for 5 ");

        blueTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField1ActionPerformed(evt);
            }
        });

        blueTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField2ActionPerformed(evt);
            }
        });

        blueTextField3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField3ActionPerformed(evt);
            }
        });

        blueTextField4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField4ActionPerformed(evt);
            }
        });

        blueTextField5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField5ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bluePanelLayout = new javax.swing.GroupLayout(bluePanel);
        bluePanel.setLayout(bluePanelLayout);
        bluePanelLayout.setHorizontalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueTextField3)
                    .addComponent(blueTextField4)
                    .addComponent(blueTextField1)
                    .addComponent(blueTextField5)
                    .addComponent(blueTextField2))
                .addContainerGap())
        );
        bluePanelLayout.setVerticalGroup(
            bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanelLayout.createSequentialGroup()
                .addComponent(blueLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        blueLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/yellow.PNG"))); // NOI18N
        blueLabel6.setText("Input details 6-10");

        blueLabel7.setText("Input for 6 ");

        blueLabel8.setText("Input for 7");

        blueLabel9.setText("Input for 8");

        blueLabel10.setText("Input for 9");

        blueLabel11.setText("Input for 10");

        blueTextField6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField6ActionPerformed(evt);
            }
        });

        blueTextField7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField7ActionPerformed(evt);
            }
        });

        blueTextField8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField8ActionPerformed(evt);
            }
        });

        blueTextField9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField9ActionPerformed(evt);
            }
        });

        blueTextField10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bluePanel1Layout = new javax.swing.GroupLayout(bluePanel1);
        bluePanel1.setLayout(bluePanel1Layout);
        bluePanel1Layout.setHorizontalGroup(
            bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanel1Layout.createSequentialGroup()
                .addGroup(bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueTextField8, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(blueTextField9)
                    .addComponent(blueTextField6)
                    .addComponent(blueTextField10, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                    .addComponent(blueTextField7, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE))
                .addContainerGap())
        );
        bluePanel1Layout.setVerticalGroup(
            bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanel1Layout.createSequentialGroup()
                .addComponent(blueLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(bluePanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        blueLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/Light_yello.PNG"))); // NOI18N
        blueLabel12.setText("Input details 11-14");

        blueLabel13.setText("Input for 11");

        blueLabel14.setText("Input for 12");

        blueLabel15.setText("Input for 13 ");

        blueLabel16.setText("Input for 14");

        blueTextField11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField11ActionPerformed(evt);
            }
        });

        blueTextField12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField12ActionPerformed(evt);
            }
        });

        blueTextField13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField13ActionPerformed(evt);
            }
        });

        blueTextField14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField14ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bluePanel2Layout = new javax.swing.GroupLayout(bluePanel2);
        bluePanel2.setLayout(bluePanel2Layout);
        bluePanel2Layout.setHorizontalGroup(
            bluePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanel2Layout.createSequentialGroup()
                .addGroup(bluePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueLabel12, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel13, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel16, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel15, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel14, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueTextField13, javax.swing.GroupLayout.DEFAULT_SIZE, 179, Short.MAX_VALUE)
                    .addComponent(blueTextField14)
                    .addComponent(blueTextField11)
                    .addComponent(blueTextField12))
                .addContainerGap())
        );
        bluePanel2Layout.setVerticalGroup(
            bluePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanel2Layout.createSequentialGroup()
                .addComponent(blueLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bluePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel13, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel14, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel16, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        blueLabel18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/green.PNG"))); // NOI18N
        blueLabel18.setText("Input details 15-16");

        blueLabel19.setText("Input for 15");

        blueLabel20.setText("Input for 16");

        blueTextField16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField16ActionPerformed(evt);
            }
        });

        blueTextField17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                blueTextField17ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout bluePanel3Layout = new javax.swing.GroupLayout(bluePanel3);
        bluePanel3.setLayout(bluePanel3Layout);
        bluePanel3Layout.setHorizontalGroup(
            bluePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanel3Layout.createSequentialGroup()
                .addGroup(bluePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(blueLabel18, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel19, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(blueLabel20, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(bluePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(blueTextField16)
                    .addComponent(blueTextField17))
                .addContainerGap())
        );
        bluePanel3Layout.setVerticalGroup(
            bluePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bluePanel3Layout.createSequentialGroup()
                .addComponent(blueLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(bluePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel19, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(bluePanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(blueLabel20, javax.swing.GroupLayout.PREFERRED_SIZE, 24, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(blueTextField17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout dataPanelLayout = new javax.swing.GroupLayout(dataPanel);
        dataPanel.setLayout(dataPanelLayout);
        dataPanelLayout.setHorizontalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bluePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(bluePanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 22, Short.MAX_VALUE))
                    .addGroup(dataPanelLayout.createSequentialGroup()
                        .addComponent(bluePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addContainerGap())))
        );
        dataPanelLayout.setVerticalGroup(
            dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(dataPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(bluePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bluePanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35)
                .addGroup(dataPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(bluePanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(bluePanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(40, 40, 40))
        );

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));

        myButton.setBackground(new java.awt.Color(0, 0, 255));
        myButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        myButton.setText("LOGIN");
        myButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                myButtonActionPerformed(evt);
            }
        });

        cancelButton.setBackground(new java.awt.Color(255, 0, 0));
        cancelButton.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        cancelButton.setText("CANCEL");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout buttonPanelLayout = new javax.swing.GroupLayout(buttonPanel);
        buttonPanel.setLayout(buttonPanelLayout);
        buttonPanelLayout.setHorizontalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                .addContainerGap(417, Short.MAX_VALUE)
                .addComponent(myButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(157, 157, 157))
            .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(buttonPanelLayout.createSequentialGroup()
                    .addGap(140, 140, 140)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 224, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(434, Short.MAX_VALUE)))
        );
        buttonPanelLayout.setVerticalGroup(
            buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(buttonPanelLayout.createSequentialGroup()
                .addGap(23, 23, 23)
                .addComponent(myButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(23, Short.MAX_VALUE))
            .addGroup(buttonPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, buttonPanelLayout.createSequentialGroup()
                    .addContainerGap(25, Short.MAX_VALUE)
                    .addComponent(cancelButton, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(21, 21, 21)))
        );

        userNameLabel.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        userNameLabel.setText("User Name");

        javax.swing.GroupLayout imagePanelLayout = new javax.swing.GroupLayout(imagePanel);
        imagePanel.setLayout(imagePanelLayout);
        imagePanelLayout.setHorizontalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, imagePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(handPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addComponent(userNameLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 187, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(userNameTextField)
                        .addGap(12, 12, 12)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );
        imagePanelLayout.setVerticalGroup(
            imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(imagePanelLayout.createSequentialGroup()
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(dataPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(handPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())
                    .addGroup(imagePanelLayout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(imagePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(userNameLabel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(userNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );

        javax.swing.GroupLayout mainPanelLayout = new javax.swing.GroupLayout(mainPanel);
        mainPanel.setLayout(mainPanelLayout);
        mainPanelLayout.setHorizontalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(titlePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(imagePanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        mainPanelLayout.setVerticalGroup(
            mainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(mainPanelLayout.createSequentialGroup()
                .addComponent(titlePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(imagePanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(mainPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void blueTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField1ActionPerformed

    private void blueTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField2ActionPerformed

    private void blueTextField3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField3ActionPerformed

    private void blueTextField4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField4ActionPerformed

    private void blueTextField5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField5ActionPerformed

    private void blueTextField6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField6ActionPerformed

    private void blueTextField7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField7ActionPerformed

    private void blueTextField8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField8ActionPerformed

    private void blueTextField9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField9ActionPerformed

    private void blueTextField10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField10ActionPerformed

    private void blueTextField11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField11ActionPerformed

    private void blueTextField12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField12ActionPerformed

    private void blueTextField13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField13ActionPerformed

    private void blueTextField14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField14ActionPerformed

    private void blueTextField16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField16ActionPerformed

    private void blueTextField17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_blueTextField17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_blueTextField17ActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
        new LoginORSignup(this, rootPaneCheckingEnabled).setVisible(true);
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void myButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_myButtonActionPerformed
        String name = myButton.getText();
        String text_1=blueTextField1.getText();
        String text_2=blueTextField2.getText();
        String text_3=blueTextField3.getText();
        String text_4=blueTextField4.getText();
        String text_5=blueTextField5.getText();
        String text_6=blueTextField6.getText();
        String text_7=blueTextField7.getText();
        String text_8=blueTextField8.getText();
        String text_9=blueTextField9.getText();
        String text_10=blueTextField10.getText();
        String text_11=blueTextField11.getText();
        String text_12=blueTextField12.getText();
        String text_13=blueTextField13.getText();
        String text_14=blueTextField14.getText();
        String text_16=blueTextField16.getText();
        String text_17=blueTextField17.getText();
        String text_18=userNameTextField.getText();
        System.out.println("isFilled " + isFilled());
        System.out.println("buttonNM " + name);
        if (isFilled()) {
            if ("SIGN UP".equals(name)) {
                try {
                    Hand_Detail hand_Detail = new Hand_Detail(text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, text_12, text_13, text_14, text_16, text_17,text_18);
                    int addUserValue=new HandDetailController().addNewUser(hand_Detail);
                    System.out.println("add  "+addUserValue);
                    if(addUserValue==1){
                        JOptionPane.showMessageDialog(rootPane, "Successfully added.");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Fail to add.");
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        }
        if(isFilled1()){
            if ("LOG IN".equals(name)) {
                    Hand_Detail hand_Detail = new Hand_Detail(text_1, text_2, text_3, text_4, text_5, text_6, text_7, text_8, text_9, text_10, text_11, text_12, text_13, text_14, text_16, text_17);
                    String searchUser ;
                    try {
                    searchUser= new HandDetailController().searchUser(hand_Detail);
                     if(searchUser==null){
                        JOptionPane.showMessageDialog(rootPane, "No user exist.");
                    }else{
                        JOptionPane.showMessageDialog(rootPane, "Welcome "+searchUser);
                        this.dispose();
                         new WelcomeUser(this, rootPaneCheckingEnabled).setVisible(true);
                    }
                } catch (ClassNotFoundException | SQLException ex) {
                    Logger.getLogger(LoginForm.class.getName()).log(Level.SEVERE, null, ex);
                }
                   

            }
        }

    }//GEN-LAST:event_myButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoginForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LoginForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addUserLabel;
    private javax.swing.JLabel blueLabel;
    private javax.swing.JLabel blueLabel1;
    private javax.swing.JLabel blueLabel10;
    private javax.swing.JLabel blueLabel11;
    private javax.swing.JLabel blueLabel12;
    private javax.swing.JLabel blueLabel13;
    private javax.swing.JLabel blueLabel14;
    private javax.swing.JLabel blueLabel15;
    private javax.swing.JLabel blueLabel16;
    private javax.swing.JLabel blueLabel18;
    private javax.swing.JLabel blueLabel19;
    private javax.swing.JLabel blueLabel2;
    private javax.swing.JLabel blueLabel20;
    private javax.swing.JLabel blueLabel3;
    private javax.swing.JLabel blueLabel4;
    private javax.swing.JLabel blueLabel5;
    private javax.swing.JLabel blueLabel6;
    private javax.swing.JLabel blueLabel7;
    private javax.swing.JLabel blueLabel8;
    private javax.swing.JLabel blueLabel9;
    private javax.swing.JPanel bluePanel;
    private javax.swing.JPanel bluePanel1;
    private javax.swing.JPanel bluePanel2;
    private javax.swing.JPanel bluePanel3;
    private javax.swing.JTextField blueTextField1;
    private javax.swing.JTextField blueTextField10;
    private javax.swing.JTextField blueTextField11;
    private javax.swing.JTextField blueTextField12;
    private javax.swing.JTextField blueTextField13;
    private javax.swing.JTextField blueTextField14;
    private javax.swing.JTextField blueTextField16;
    private javax.swing.JTextField blueTextField17;
    private javax.swing.JTextField blueTextField2;
    private javax.swing.JTextField blueTextField3;
    private javax.swing.JTextField blueTextField4;
    private javax.swing.JTextField blueTextField5;
    private javax.swing.JTextField blueTextField6;
    private javax.swing.JTextField blueTextField7;
    private javax.swing.JTextField blueTextField8;
    private javax.swing.JTextField blueTextField9;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JButton cancelButton;
    private javax.swing.JPanel dataPanel;
    private javax.swing.JPanel handPanel;
    private javax.swing.JLabel handPic;
    private javax.swing.JPanel imagePanel;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JPanel mainPanel;
    private javax.swing.JButton myButton;
    private javax.swing.JPanel titlePanel;
    private javax.swing.JLabel userNameLabel;
    private javax.swing.JTextField userNameTextField;
    // End of variables declaration//GEN-END:variables

    private boolean isFilled() {
        boolean text1_5=!(blueTextField1.getText().isEmpty() && blueTextField2.getText().isEmpty() && blueTextField3.getText().isEmpty() && blueTextField4.getText().isEmpty() && blueTextField5.getText().isEmpty());
        boolean text6_10=!(blueTextField6.getText().isEmpty() && blueTextField7.getText().isEmpty() && blueTextField8.getText().isEmpty() && blueTextField9.getText().isEmpty() && blueTextField10.getText().isEmpty());
        boolean text11_14=!(blueTextField11.getText().isEmpty() && blueTextField12.getText().isEmpty() && blueTextField13.getText().isEmpty() && blueTextField14.getText().isEmpty());
        boolean text16_17=!(blueTextField16.getText().isEmpty() && blueTextField17.getText().isEmpty() );
        boolean user_text=!(userNameTextField.getText().isEmpty());
        
        return text1_5 && text6_10 && text11_14 && text16_17 && user_text;
    }
    
    private boolean isFilled1() {
        boolean text1_5=!(blueTextField1.getText().isEmpty() && blueTextField2.getText().isEmpty() && blueTextField3.getText().isEmpty() && blueTextField4.getText().isEmpty() && blueTextField5.getText().isEmpty());
        boolean text6_10=!(blueTextField6.getText().isEmpty() && blueTextField7.getText().isEmpty() && blueTextField8.getText().isEmpty() && blueTextField9.getText().isEmpty() && blueTextField10.getText().isEmpty());
        boolean text11_14=!(blueTextField11.getText().isEmpty() && blueTextField12.getText().isEmpty() && blueTextField13.getText().isEmpty() && blueTextField14.getText().isEmpty());
        boolean text16_17=!(blueTextField16.getText().isEmpty() && blueTextField17.getText().isEmpty() );
        
        return text1_5 && text6_10 && text11_14 && text16_17 ;
    }
}
